# Generated by Django 4.2.7 on 2023-11-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedb',
            name='empid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
